services:
  # MySQL Database
  mysql_db:
    image: mysql:latest
    container_name: speekly_db
    environment:
      MYSQL_DATABASE: speekly_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: